version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
          
  letsencrypt:
    image: duch/letsencrypt-nginx-proxy-companion:latest
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx_mtome:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=mtome.xyz,www.mtome.xyz
      - LETSENCRYPT_HOST=mtome.xyz,www.mtome.xyz
      - LETSENCRYPT_EMAIL=mrtn.tome@gmail.com

volumes:
  certs:
  html:
  vhostd:
  confd:
