version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "1313:80"
    volumes:
      - ../public:/usr/share/nginx/html:ro
      - ../nginx.conf:/etc/nginx/nginx.conf:ro


